import {useEffect,useState} from 'react';
import {api,money,itemCalc,draftTotals,type Draft,type Boot} from './App';
import {RecordActions,ExtraAttachments} from './workflow';
import {alert,confirm,prompt,useModalLock} from './dialogs';
const number=(v:unknown)=>Number(v)||0;
const total=(d:Draft)=>draftTotals(d).total;
const final=(d:Draft)=>draftTotals(d).final;
const when=(s:string)=>s?new Date(s).toLocaleString():'';
const matches=(d:Draft,f:string)=>f==='ALL'||f==='PENDING'&&d.status==='PENDING_INTERNAL_APPROVAL'||f==='APPROVED'&&!!d.internal_approver||f==='PO'&&d.status.startsWith('CUSTOMER_PO')||f==='WAIT_PO'&&['INTERNALLY_APPROVED','CUSTOMER_PO_PARTIAL'].includes(d.status)||f==='DEADLINE'&&!d.status.startsWith('CUSTOMER_PO')&&!!d.quotation_due_date&&new Date(d.quotation_due_date).getTime()<Date.now()+3*86400000;

export function History({records,filter='ALL',open,refresh}:{records:Draft[];filter?:string;open:(d:Draft)=>void;refresh?:()=>void}){
 const [search,setSearch]=useState(''),[page,setPage]=useState(0),[visible,setVisible]=useState(false),[archived,setArchived]=useState(false);
 useEffect(()=>setPage(0),[filter,search,archived]);
 useEffect(()=>{if(filter!=='ALL')setVisible(true)},[filter]);
 const groups=new Map<string,Draft[]>();
 const byId=new Map(records.map(d=>[d.draft_id,d]));
 const root=(d:Draft)=>{const seen=new Set<string>();while(d.previous_draft_id&&byId.has(d.previous_draft_id)&&!seen.has(d.draft_id)){seen.add(d.draft_id);d=byId.get(d.previous_draft_id)!}return d.draft_id};
 records.filter(d=>archived||!d.pilot_meta?.archived).forEach(d=>{const key=root(d);groups.set(key,[...(groups.get(key)||[]),d])});
 const list=[...groups.values()].map(g=>g.sort((a,b)=>number(b.revision.slice(1))-number(a.revision.slice(1)))).filter(g=>g.some(d=>matches(d,filter))&&g.some(d=>`${d.q_code} ${d.customer} ${d.rfq_reference}`.toLowerCase().includes(search.toLowerCase()))).sort((a,b)=>b[0].updated_at.localeCompare(a[0].updated_at));
 const archivedCount=new Set(records.filter(d=>d.pilot_meta?.archived).map(root)).size;
 const max=Math.max(0,Math.ceil(list.length/10)-1),safe=Math.min(page,max);
 return <section className="card quotation-history"><button className="history-toggle" aria-expanded={visible} onClick={()=>setVisible(!visible)}>{visible?'Hide':'Show'} Quotation History <span>{list.length} quotations</span></button>{visible&&<><div className="card-head history-toolbar"><div><h2>Quotation History</h2><p>Latest revision first. Expand a quotation to review its permanent revision record.</p></div><div className="history-filters"><input aria-label="Search quotations" placeholder="Search Q-Code, customer or RFQ" value={search} onChange={e=>setSearch(e.target.value)}/><label className="archive-filter"><input type="checkbox" checked={archived} onChange={e=>setArchived(e.target.checked)}/> Show archived ({archivedCount})</label></div></div><div className="history-head"><span>Quotation / customer</span><span>RFQ</span><span>Final total</span><span>Status</span></div>{list.slice(safe*10,safe*10+10).map(g=><details key={g[0].draft_id} className="history-group"><summary><span><button className="text-action" onClick={e=>{e.preventDefault();open(g[0])}}>{g[0].q_code||'Q-Code pending'} · {g[0].revision}</button><small>{g[0].customer} · {g.length} revision(s)</small></span><span>{g[0].rfq_reference}</span><strong>{money(final(g[0]))}</strong><span>{g[0].pilot_meta?.archived&&<b className="pill archived">Archived</b>}<small>{g[0].status.replaceAll('_',' ')}</small><small>{when(g[0].updated_at)}</small></span></summary><div className="revision-list">{refresh&&<RecordActions draft={g[0]} done={refresh}/>} {g.map(d=><button key={d.draft_id} onClick={()=>open(d)}>{d.revision} · {d.q_code||'Pending'} · {d.status.replaceAll('_',' ')}{d.pilot_meta?.archived?' · Archived':''} · {when(d.updated_at)}</button>)}</div></details>)}{!list.length&&<div className="empty">No matching quotations.</div>}<div className="history-footer"><span>{list.length} quotations · Page {safe+1} of {max+1}</span><button className="secondary" disabled={safe===0} onClick={()=>setPage(safe-1)}>Previous</button><button className="secondary" disabled={safe===max} onClick={()=>setPage(safe+1)}>Next</button></div></>}</section>
}

export function Executive({boot,role,open,refresh,settings}:{boot:Boot;role:string;open:(d:Draft)=>void;refresh:()=>Promise<void>;settings:()=>void}){
 const [filter,setFilter]=useState('PENDING');
 const pending=boot.saved.filter(d=>matches(d,'PENDING')),po=boot.saved.filter(d=>matches(d,'WAIT_PO')),due=boot.saved.filter(d=>matches(d,'DEADLINE'));
 const employees=[...new Set(boot.saved.map(d=>d.prepared_by))].map(name=>{const records=boot.saved.filter(d=>d.prepared_by===name);const timed=records.filter(d=>d.submitted_at&&d.quotation_due_date);const onTime=timed.filter(d=>new Date(d.submitted_at).getTime()<=new Date(d.quotation_due_date+'T23:59:59+08:00').getTime()).length;const measured=records.filter(d=>d.submitted_at&&d.created_at);const hours=measured.length?measured.reduce((s,d)=>s+Math.max(0,new Date(d.submitted_at).getTime()-new Date(d.created_at).getTime())/3600000,0)/measured.length:null;return{name,onTime:timed.length?Math.round(onTime/timed.length*100):null,hours,submitted:records.filter(d=>!['QUOTATION_DRAFT','RFQ_RECEIVED'].includes(d.status)).length,approved:records.filter(d=>!!d.internal_approver).length}}).sort((a,b)=>(b.onTime??-1)-(a.onTime??-1)||b.submitted-a.submitted);
 return <><div className="leadership-hero ceo"><div><div className="eyebrow">{role==='CEO'?'Executive workspace':'Delegated approval workspace'}</div><h1>{role==='CEO'?'CEO Command Center':'Approver Dashboard'}</h1><p>Clear decisions. Timely quotations. Customer follow-through.</p></div><div className="head-actions"><button className="primary" onClick={async()=>{const d=await api('create_new');d.prepared_by=role==='CEO'?'Macrotech CEO':'Delegated Approver';open(d)}}>+ New Quotation</button><button className="secondary" onClick={settings}>Requests ({boot.platform.contactRequests.filter(r=>r.status==='PENDING').length}) & settings</button></div></div><div className="stats executive-stats">{[['PENDING','Approval queue',pending.length],['APPROVED','Approved quotations',new Set(boot.saved.filter(d=>!!d.internal_approver).map(d=>d.q_code||d.draft_id)).size],['WAIT_PO','Pending customer POs',po.length],['DEADLINE','Due soon / overdue',due.length],['ALL','Quotation portfolio',boot.saved.length]].map(([key,label,value])=><button key={key} className={`stat stat-button ${filter===key?'selected':''}`} onClick={()=>setFilter(String(key))}><span>{label}</span><strong>{value}</strong></button>)}</div><div className="executive-grid"><div><History records={boot.saved} filter={filter} open={open} refresh={refresh}/></div><aside><section className="card deadline-panel"><h2>Release deadlines</h2><p>Due within 3 days or overdue; release not confirmed. Approved quotes remain here until delivery can be verified. Approval is not proof of customer delivery.</p>{due.length?due.map(d=><button className="deadline-row" key={d.draft_id} onClick={()=>open(d)}><b>{d.q_code||'Pending'} · {d.customer}</b><span>{d.quotation_due_date} · {d.prepared_by}</span></button>):<div className="empty">No approaching approval deadlines.</div>}</section><section className="card deadline-panel"><h2>Employee quotation efficiency</h2><p>Ranked by on-time submission percentage. Preparation time ends at submission and excludes approval waiting. Historical entries without timestamps are not scored. Customer release performance awaits email integration.</p>{employees.map((e,i)=><div className="ranking-row" key={e.name}><b>{i+1}. {e.name}</b><span>{e.submitted} submitted · {e.approved} approved</span><span>{e.onTime===null?"Not yet measured":`${e.onTime}% on time · ${e.hours?.toFixed(1)}h average preparation`}</span></div>)}</section></aside></div><button className="ghost" onClick={refresh}>Refresh command center</button></>
}

export function Review({draft,role,next,details,back}:{draft:Draft;role:string;next:()=>Promise<void>;details:()=>void;back:()=>void}){
 const [percent,setPercent]=useState(draft.discount_requested_percent||'0'),[busy,setBusy]=useState(false);
 useEffect(()=>setPercent(draft.discount_requested_percent||'0'),[draft.draft_id]);
 const options=draft.items.map(i=>i.supplier_options.find(s=>s.id===i.selected_supplier_id)).filter(Boolean);
 const rate=(key:'markup_multiplier'|'duty_rate'|'safety_factor_rate',suffix:string,factor=1)=>{const values=[...new Set(options.map(s=>String(Number((number(s![key])*factor).toFixed(6)))))];return values.length===1?values[0]+suffix:'Varies by item'};
 const grand=total(draft),discount=Math.round(grand*number(percent))/100;
 const reject=async()=>{const reason=await prompt('Reason for return for correction','');if(!reason?.trim())return;setBusy(true);try{await api('reject',draft,reason);await alert('Returned for correction. The employee must create a new revision. Nothing was emailed.');await next()}catch(e){await alert(String(e))}finally{setBusy(false)}};
 const approve=async()=>{if(!await confirm(`Approve ${draft.q_code} for ${draft.customer}?\nGrand Total: ${money(grand)}\nDiscount: ${percent}% (${money(discount)})\nFinal Total: ${money(grand-discount)}`))return;setBusy(true);try{const d:Draft=await api('approve_percent',draft,role==='CEO'?'Macrotech CEO':'Delegated Approver',percent);const tracker=d.pilot_meta?.sync?.state==='SYNCED'?'\nTest master synchronized.':'\nApproval saved. Test master update pending; see Settings → My Tracker.';await alert(`✓ ${d.q_code} approved\n${d.customer}\nGrand Total: ${money(total(d))}\nApproved discount: ${d.discount_approved_percent}% · ${money(number(d.discount_amount))}\nFinal Total: ${money(final(d))}\nApproved by ${d.internal_approver}${tracker}`);await next()}catch(e){await alert(String(e))}finally{setBusy(false)}};
 return <div className="approval-focus"><button className="ghost" onClick={back}>← Approval queue</button><div className="review-heading"><div><div className="eyebrow">Internal Macrotech approval</div><h1>{draft.customer}</h1><p>{draft.rfq_reference} · Prepared by {draft.prepared_by}</p></div><span className="review-qcode">{draft.q_code}</span></div><section className="card financial-review"><div className="review-grand"><span>GRAND TOTAL</span><strong>{money(grand)}</strong><small>Before approved discount</small></div><div className="review-metrics"><div><span>Mark-Up</span><b>{rate('markup_multiplier','×')}</b></div><div><span>Duties / forwarder rate</span><b>{rate('duty_rate','%',100)}</b></div><div><span>Safety Factor</span><b>{rate('safety_factor_rate','%',100)}</b></div><div><span>VAT included</span><b>{money(grand-grand/1.12)} · 12%</b></div></div><div className="review-note"><span>Employee submission comment</span><p>{draft.employee_comments||'No comment provided.'}</p></div><div className="discount-review"><div><label>Approve / modify requested discount (%)</label><input aria-label="Approved discount percentage" type="number" min="0" max="100" step="0.01" value={percent} onChange={e=>setPercent(e.target.value)}/><small>Requested: {draft.discount_requested_percent||'0'}%</small></div><div><span>Discount amount</span><b>{money(discount)}</b><span>Total After Discount</span><strong>{money(grand-discount)}</strong></div></div><div className="dialog-actions"><button className="secondary" onClick={details}>View quotation details</button><button className="danger" disabled={busy} onClick={()=>void reject()}>Reject / return for correction</button><button className="primary" disabled={busy||percent===''||!Number.isFinite(Number(percent))||number(percent)<0||number(percent)>100} onClick={approve}>{busy?'Recording approval…':'Approve & next request'}</button></div></section><details className="card review-breakdown"><summary>View item financial breakdown</summary><table className="table"><thead><tr><th>Item</th><th>Mark-Up</th><th>Duty rate</th><th>Safety factor</th><th>VAT-inclusive amount</th></tr></thead><tbody>{draft.items.map(i=>{const s=i.supplier_options.find(s=>s.id===i.selected_supplier_id);return <tr key={i.item_no}><td>{i.item_no}</td><td>{s?.markup_multiplier}×</td><td>{number(s?.duty_rate)*100}%</td><td>{number(s?.safety_factor_rate)*100}%</td><td>{money(itemCalc(i).vatIn)}</td></tr>})}</tbody></table></details></div>
}

export function Composer({draft,close}:{draft:Draft;close:()=>void}){
 useModalLock();
 const key=`macrotech-compose-${draft.draft_id}`;
 const [form,setForm]=useState(()=>{try{const old=localStorage.getItem(key);if(old)return JSON.parse(old)}catch{}return{from:'',to:draft.buyer.match(/[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}/i)?.[0]||'',cc:'',bcc:'',subject:`Macrotech Quotation ${draft.q_code} ${draft.revision} · ${draft.rfq_reference}`,message:`Dear Customer,\n\nPlease find attached our approved quotation for ${draft.rfq_reference}.\n\nThank you,\n${draft.prepared_by}`}});
 return <div className="modal"><div className="dialog composer" role="dialog" aria-modal="true" aria-label="Email approved quotation"><div className="dialog-head"><div><div className="eyebrow">Customer correspondence · Local preview</div><h2>Email approved quotation</h2><p>Gmail sending is not connected in this build. Saving this draft does not send or mark the quotation released.</p></div><button className="ghost" onClick={close}>✕</button></div>{['from','to','cc','bcc','subject'].map(k=><div className="field" key={k}><label>{k==='from'?'From · Employee Gmail':k.toUpperCase()}</label><input value={form[k]} onChange={e=>setForm({...form,[k]:e.target.value})}/></div>)}<div className="field"><label>Message</label><textarea rows={6} value={form.message} onChange={e=>setForm({...form,message:e.target.value})}/></div><div className="attachment"><b>Approved PDF · {draft.q_code} · {draft.revision}</b><button className="secondary" disabled={!draft.approved_pdf_path} onClick={()=>api('open_path',draft.approved_pdf_path)}>Review attachment</button></div><ExtraAttachments draft={draft}/><div className="dialog-actions"><button className="secondary" onClick={close}>Close</button><button className="primary" onClick={async()=>{localStorage.setItem(key,JSON.stringify(form));await alert('Email draft saved on this computer. Nothing was sent.');close()}}>Save email draft</button><button className="secondary" disabled title="Requires tested Gmail integration">Email with Gmail · Not connected</button></div></div></div>
}
